/**
 * A fallback map used by Telegram.
 */
const FALLBACKS = new Map([
  [`chat_adminText`, `chat_inTimeText`],
  [`chat_adminSelectedText`, `chat_inTimeSelectedText`],
  [`key_player_progressCachedBackground`, `player_progressBackground`],
  [`chat_inAudioCacheSeekbar`, `chat_inAudioSeekbar`],
  [`chat_outAudioCacheSeekbar`, `chat_outAudioSeekbar`],
  [`chat_emojiSearchBackground`, `chat_emojiPanelStickerPackSelector`],
  [`location_sendLiveLocationIcon`, `location_sendLocationIcon`],
  [`changephoneinfo_image2`, `featuredStickers_addButton`],
  [`key_graySectionText`, `windowBackgroundWhiteGrayText2`],
  [`chat_inMediaIcon`, `chat_inBubble`],
  [`chat_outMediaIcon`, `chat_outBubble`],
  [`chat_inMediaIconSelected`, `chat_inBubbleSelected`],
  [`chat_outMediaIconSelected`, `chat_outBubbleSelected`],
  [`chats_actionUnreadIcon`, `profile_actionIcon`],
  [`chats_actionUnreadBackground`, `profile_actionBackground`],
  [`chats_actionUnreadPressedBackground`, `profile_actionPressedBackground`],
  [`dialog_inlineProgressBackground`, `windowBackgroundGray`],
  [`dialog_inlineProgress`, `chats_menuItemIcon`],
  [`groupcreate_spanDelete`, `chats_actionIcon`],
  [`sharedMedia_photoPlaceholder`, `windowBackgroundGray`],
  [`chat_attachPollBackground`, `chat_attachAudioBackground`],
  [`chat_attachPollIcon`, `chat_attachAudioIcon`],
  [`chats_onlineCircle`, `windowBackgroundWhiteBlueText`],
  [`windowBackgroundWhiteBlueButton`, `windowBackgroundWhiteValueText`],
  [`windowBackgroundWhiteBlueIcon`, `windowBackgroundWhiteValueText`],
  [`undo_background`, `chat_gifSaveHintBackground`],
  [`undo_cancelColor`, `chat_gifSaveHintText`],
  [`undo_infoColor`, `chat_gifSaveHintText`],
  [`windowBackgroundUnchecked`, `windowBackgroundWhite`],
  [`windowBackgroundChecked`, `windowBackgroundWhite`],
  [`switchTrackBlue`, `switchTrack`],
  [`switchTrackBlueChecked`, `switchTrackChecked`],
  [`switchTrackBlueThumb`, `windowBackgroundWhite`],
  [`switchTrackBlueThumbChecked`, `windowBackgroundWhite`],
  [`windowBackgroundCheckText`, `windowBackgroundWhiteBlackText`],
  [`contextProgressInner4`, `contextProgressInner1`],
  [`contextProgressOuter4`, `contextProgressOuter1`],
  [`switchTrackBlueSelector`, `listSelector`],
  [`switchTrackBlueSelectorChecked`, `listSelector`],
  [`chat_emojiBottomPanelIcon`, `chat_emojiPanelIcon`],
  [`chat_emojiSearchIcon`, `chat_emojiPanelIcon`],
  [`chat_emojiPanelStickerSetNameHighlight`, `windowBackgroundWhiteBlueText4`],
  [`chat_emojiPanelStickerPackSelectorLine`, `chat_emojiPanelIconSelected`],
  [`sharedMedia_actionMode`, `actionBarDefault`],
  [`key_sheet_scrollUp`, `chat_emojiPanelStickerPackSelector`],
  [`sheet_other`, `player_actionBarItems`],
  [`dialogSearchBackground`, `chat_emojiPanelStickerPackSelector`],
  [`dialogSearchHint`, `chat_emojiPanelIcon`],
  [`dialogSearchIcon`, `chat_emojiPanelIcon`],
  [`dialogSearchText`, `windowBackgroundWhiteBlackText`],
  [`dialogFloatingButton`, `dialogRoundCheckBox`],
  [`dialogFloatingButtonPressed`, `dialogRoundCheckBox`],
  [`dialogFloatingIcon`, `dialogRoundCheckBoxCheck`],
  [`dialogShadowLine`, `chat_emojiPanelShadowLine`],
  [`actionBarDefaultArchived`, `actionBarDefault`],
  [`actionBarDefaultArchivedSelector`, `actionBarDefaultSelector`],
  [`actionBarDefaultArchivedIcon`, `actionBarDefaultIcon`],
  [`actionBarDefaultArchivedTitle`, `actionBarDefaultTitle`],
  [`actionBarDefaultArchivedSearch`, `actionBarDefaultSearch`],
  [
    `actionBarDefaultArchivedSearchPlaceholder`,
    `actionBarDefaultSearchPlaceholder`,
  ],
  [`chats_message_threeLines`, `chats_message`],
  [`chats_nameMessage_threeLines`, `chats_nameMessage`],
  [`chats_nameArchived`, `chats_name`],
  [`chats_nameMessageArchived`, `chats_nameMessage`],
  [`chats_nameMessageArchived_threeLines`, `chats_nameMessage`],
  [`chats_messageArchived`, `chats_message`],
  [`avatar_backgroundArchived`, `chats_unreadCounterMuted`],
  [`avatar_backgroundArchivedHidden`, `chats_unreadCounterMuted`],
  [`chats_archiveBackground`, `chats_actionBackground`],
  [`chats_archivePinBackground`, `chats_unreadCounterMuted`],
  [`chats_archiveIcon`, `chats_actionIcon`],
  [`chats_archiveText`, `chats_actionIcon`],
  [`actionBarDefaultSubmenuItemIcon`, `dialogIcon`],
  [`checkboxDisabled`, `chats_unreadCounterMuted`],
  [`chat_status`, `actionBarDefaultSubtitle`],
  [`chat_inGreenCall`, `calls_callReceivedGreenIcon`],
  [`chat_inRedCall`, `calls_callReceivedRedIcon`],
  [`chat_outGreenCall`, `calls_callReceivedGreenIcon`],
  [`actionBarTabActiveText`, `actionBarDefaultTitle`],
  [`actionBarTabUnactiveText`, `actionBarDefaultSubtitle`],
  [`actionBarTabLine`, `actionBarDefaultTitle`],
  [`actionBarTabSelector`, `actionBarDefaultSelector`],
  [`profile_status`, `avatar_subtitleInProfileBlue`],
  [`chats_menuTopBackgroundCats`, `avatar_backgroundActionBarBlue`],
  [`chat_messagePanelSendPressed`, `key_chat_messagePanelVoicePressed`],
  [`chat_attachPermissionImage`, `dialogTextBlack`],
  [`chat_attachPermissionMark`, `chat_sentError`],
  [`chat_attachPermissionText`, `dialogTextBlack`],
  [`chat_attachEmptyImage`, `emptyListPlaceholder`],
  [`actionBarBrowser`, `actionBarDefault`],
  [`chats_sentReadCheck`, `chats_sentCheck`],
  [`chat_outSentCheckRead`, `chat_outSentCheck`],
  [`chat_outSentCheckReadSelected`, `chat_outSentCheckSelected`],
]);

export default FALLBACKS;
