// This file was automatically generated by .attheme default theme
// generator, available at:
//     https://gitlab.com/snejugal/attheme-default-theme-generator

import Attheme from "..";
import { Color } from "../types";

/**
 * Generates the Day theme.
 */
const day = () =>
  new Attheme([
    [
      `actionBarDefault`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchived`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchivedIcon`,
      {
        red: 45,
        green: 48,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchivedTitle`,
      {
        red: 51,
        green: 56,
        blue: 60,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultIcon`,
      {
        red: 64,
        green: 78,
        blue: 86,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSearch`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSearchPlaceholder`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 136,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSelector`,
      {
        red: 42,
        green: 47,
        blue: 53,
        alpha: 16,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubtitle`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultTitle`,
      {
        red: 51,
        green: 51,
        blue: 51,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabActiveText`,
      {
        red: 15,
        green: 152,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabLine`,
      {
        red: 47,
        green: 162,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabSelector`,
      {
        red: 42,
        green: 47,
        blue: 53,
        alpha: 8,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabUnactiveText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarWhiteSelector`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 16,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconBlue`,
      {
        red: 66,
        green: 73,
        blue: 82,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconCyan`,
      {
        red: 129,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconGreen`,
      {
        red: 129,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconOrange`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconPink`,
      {
        red: 123,
        green: 123,
        blue: 129,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconRed`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarIconViolet`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorBlue`,
      {
        red: 53,
        green: 58,
        blue: 66,
        alpha: 15,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorCyan`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorGreen`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorOrange`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorPink`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorRed`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorViolet`,
      {
        red: 123,
        green: 123,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarBlue`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarCyan`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarGreen`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarOrange`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarPink`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarRed`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarViolet`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundArchivedHidden`,
      {
        red: 69,
        green: 182,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundBlue`,
      {
        red: 80,
        green: 165,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundInProfileBlue`,
      {
        red: 52,
        green: 150,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundSaved`,
      {
        red: 69,
        green: 182,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageBlue`,
      {
        red: 37,
        green: 134,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessagePink`,
      {
        red: 203,
        green: 79,
        blue: 134,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageViolet`,
      {
        red: 131,
        green: 111,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileBlue`,
      {
        red: 141,
        green: 141,
        blue: 141,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileCyan`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileGreen`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileOrange`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfilePink`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileRed`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileViolet`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `calls_callReceivedGreenIcon`,
      {
        red: 47,
        green: 199,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_TextSelectionCursor`,
      {
        red: 99,
        green: 200,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_addContact`,
      {
        red: 30,
        green: 138,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_adminSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_adminText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachAudioText`,
      {
        red: 222,
        green: 71,
        blue: 71,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachContactText`,
      {
        red: 223,
        green: 160,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachFileText`,
      {
        red: 20,
        green: 168,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachGalleryText`,
      {
        red: 46,
        green: 141,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachLocationText`,
      {
        red: 60,
        green: 171,
        blue: 47,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachPollText`,
      {
        red: 223,
        green: 160,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachSendBackground`,
      {
        red: 63,
        green: 157,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botButtonText`,
      {
        red: 45,
        green: 45,
        blue: 45,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botProgress`,
      {
        red: 53,
        green: 53,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botSwitchToInlineText`,
      {
        red: 50,
        green: 138,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_editDoneIcon`,
      {
        red: 22,
        green: 141,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelBadgeBackground`,
      {
        red: 71,
        green: 167,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelNewTrending`,
      {
        red: 63,
        green: 164,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_fieldOverlayText`,
      {
        red: 49,
        green: 152,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_goDownButtonCounterBackground`,
      {
        red: 50,
        green: 158,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioCacheSeekbar`,
      {
        red: 216,
        green: 229,
        blue: 240,
        alpha: 63,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioDurationSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioDurationText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbar`,
      {
        red: 213,
        green: 218,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbarFill`,
      {
        red: 81,
        green: 163,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbarSelected`,
      {
        red: 213,
        green: 218,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSelectedProgress`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioTitleText`,
      {
        red: 41,
        green: 44,
        blue: 48,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubble`,
      {
        red: 240,
        green: 240,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubbleSelected`,
      {
        red: 234,
        green: 234,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubbleShadow`,
      {
        red: 29,
        green: 55,
        blue: 83,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactBackground`,
      {
        red: 51,
        green: 161,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactNameText`,
      {
        red: 50,
        green: 50,
        blue: 50,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileBackground`,
      {
        red: 161,
        green: 217,
        blue: 255,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileBackgroundSelected`,
      {
        red: 203,
        green: 234,
        blue: 246,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileInfoSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileInfoText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileNameText`,
      {
        red: 41,
        green: 41,
        blue: 41,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileProgress`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileProgressSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileSelectedIcon`,
      {
        red: 125,
        green: 164,
        blue: 197,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inForwardedNameText`,
      {
        red: 48,
        green: 131,
        blue: 218,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstant`,
      {
        red: 23,
        green: 137,
        blue: 222,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstantSelected`,
      {
        red: 23,
        green: 137,
        blue: 222,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoader`,
      {
        red: 72,
        green: 167,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderSelected`,
      {
        red: 51,
        green: 158,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLocationBackground`,
      {
        red: 235,
        green: 240,
        blue: 245,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLocationIcon`,
      {
        red: 158,
        green: 166,
        blue: 170,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMediaIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMediaIconSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMenuSelected`,
      {
        red: 182,
        green: 189,
        blue: 197,
        alpha: 228,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantSelectedText`,
      {
        red: 22,
        green: 137,
        blue: 218,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantText`,
      {
        red: 22,
        green: 137,
        blue: 217,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewLine`,
      {
        red: 60,
        green: 154,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyLine`,
      {
        red: 62,
        green: 145,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyMediaMessageSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyNameText`,
      {
        red: 49,
        green: 134,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSentClock`,
      {
        red: 176,
        green: 186,
        blue: 196,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSentClockSelected`,
      {
        red: 176,
        green: 186,
        blue: 196,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSiteNameText`,
      {
        red: 29,
        green: 126,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inTextSelectionHighlight`,
      {
        red: 107,
        green: 199,
        blue: 255,
        alpha: 81,
      } as Color,
    ] as [string, Color],
    [
      `chat_inTimeSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inTimeText`,
      {
        red: 147,
        green: 149,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVenueInfoSelectedText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVenueInfoText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViaBotNameText`,
      {
        red: 48,
        green: 131,
        blue: 218,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViews`,
      {
        red: 157,
        green: 160,
        blue: 163,
        alpha: 239,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViewsSelected`,
      {
        red: 157,
        green: 160,
        blue: 163,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbar`,
      {
        red: 186,
        green: 192,
        blue: 200,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbarFill`,
      {
        red: 55,
        green: 155,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbarSelected`,
      {
        red: 186,
        green: 192,
        blue: 200,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inlineResultIcon`,
      {
        red: 52,
        green: 158,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_linkSelectBackground`,
      {
        red: 114,
        green: 189,
        blue: 234,
        alpha: 61,
      } as Color,
    ] as [string, Color],
    [
      `chat_lockIcon`,
      {
        red: 45,
        green: 45,
        blue: 45,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_mediaLoaderPhotoSelected`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_mediaTimeText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkIn`,
      {
        red: 18,
        green: 122,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkOut`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelCursor`,
      {
        red: 69,
        green: 157,
        blue: 225,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelSend`,
      {
        red: 66,
        green: 162,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelShadow`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 229,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelVideoFrame`,
      {
        red: 60,
        green: 173,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelVoiceBackground`,
      {
        red: 55,
        green: 153,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageTextOut`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_muteIcon`,
      {
        red: 115,
        green: 115,
        blue: 115,
        alpha: 102,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioCacheSeekbar`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 43,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationSelectedText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioPerfomerSelectedText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioPerfomerText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioProgress`,
      {
        red: 70,
        green: 134,
        blue: 209,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbar`,
      {
        red: 157,
        green: 198,
        blue: 243,
        alpha: 101,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarFill`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarSelected`,
      {
        red: 157,
        green: 198,
        blue: 243,
        alpha: 100,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSelectedProgress`,
      {
        red: 70,
        green: 134,
        blue: 209,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioTitleText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubble`,
      {
        red: 45,
        green: 126,
        blue: 213,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleGradient`,
      {
        red: 92,
        green: 182,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleSelected`,
      {
        red: 66,
        green: 128,
        blue: 209,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleShadow`,
      {
        red: 9,
        green: 55,
        blue: 108,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactBackground`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactIcon`,
      {
        red: 31,
        green: 146,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneSelectedText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackground`,
      {
        red: 127,
        green: 179,
        blue: 231,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackgroundSelected`,
      {
        red: 127,
        green: 179,
        blue: 231,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileIcon`,
      {
        red: 157,
        green: 176,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoSelectedText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgress`,
      {
        red: 31,
        green: 146,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgressSelected`,
      {
        red: 31,
        green: 146,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileSelectedIcon`,
      {
        red: 126,
        green: 155,
        blue: 189,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outForwardedNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstant`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstantSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoader`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhoto`,
      {
        red: 157,
        green: 177,
        blue: 195,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIconSelected`,
      {
        red: 233,
        green: 238,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoSelected`,
      {
        red: 157,
        green: 176,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationBackground`,
      {
        red: 142,
        green: 190,
        blue: 233,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 228,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMediaIcon`,
      {
        red: 31,
        green: 146,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMediaIconSelected`,
      {
        red: 31,
        green: 146,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenu`,
      {
        red: 156,
        green: 205,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenuSelected`,
      {
        red: 156,
        green: 205,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantSelectedText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewLine`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyLine`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageSelectedText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMessageText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheck`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 245,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheckRead`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 245,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheckSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 245,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClock`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 112,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClockSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 112,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSiteNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTextSelectionHighlight`,
      {
        red: 114,
        green: 201,
        blue: 255,
        alpha: 150,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeSelectedText`,
      {
        red: 204,
        green: 232,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outUpCall`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoSelectedText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoText`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueNameText`,
      {
        red: 75,
        green: 154,
        blue: 212,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViaBotNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViews`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViewsSelected`,
      {
        red: 199,
        green: 230,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbar`,
      {
        red: 165,
        green: 213,
        blue: 250,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarFill`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarSelected`,
      {
        red: 165,
        green: 213,
        blue: 250,
        alpha: 229,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordedVoiceBackground`,
      {
        red: 77,
        green: 162,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordedVoiceDot`,
      {
        red: 243,
        green: 70,
        blue: 70,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelIcons`,
      {
        red: 71,
        green: 148,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelMessage`,
      {
        red: 52,
        green: 52,
        blue: 52,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelName`,
      {
        red: 37,
        green: 149,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_reportSpam`,
      {
        red: 245,
        green: 64,
        blue: 76,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_secretTimeText`,
      {
        red: 203,
        green: 219,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_secretTimerBackground`,
      {
        red: 63,
        green: 74,
        blue: 83,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_selectedBackground`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 8,
      } as Color,
    ] as [string, Color],
    [
      `chat_sentError`,
      {
        red: 255,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceBackground`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 244,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceBackgroundSelected`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 16,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceIcon`,
      {
        red: 48,
        green: 62,
        blue: 73,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceLink`,
      {
        red: 38,
        green: 141,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceText`,
      {
        red: 56,
        green: 56,
        blue: 56,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_status`,
      {
        red: 7,
        green: 133,
        blue: 217,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_stickerNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_stickerReplyLine`,
      {
        red: 49,
        green: 148,
        blue: 221,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_stickerReplyMessageText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_stickerReplyNameText`,
      {
        red: 43,
        green: 137,
        blue: 219,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_textSelectBackground`,
      {
        red: 122,
        green: 192,
        blue: 237,
        alpha: 99,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelLine`,
      {
        red: 71,
        green: 161,
        blue: 254,
        alpha: 234,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelMessage`,
      {
        red: 127,
        green: 134,
        blue: 137,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelTitle`,
      {
        red: 65,
        green: 150,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartArrowIcon`,
      {
        red: 198,
        green: 231,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartBackground`,
      {
        red: 52,
        green: 153,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_wallpaper`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionBackground`,
      {
        red: 81,
        green: 162,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionMessage`,
      {
        red: 37,
        green: 121,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionPressedBackground`,
      {
        red: 54,
        green: 141,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_archiveBackground`,
      {
        red: 83,
        green: 166,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_archivePinBackground`,
      {
        red: 187,
        green: 194,
        blue: 207,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_attachMessage`,
      {
        red: 37,
        green: 121,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_draft`,
      {
        red: 227,
        green: 34,
        blue: 70,
        alpha: 250,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuBackground`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuCloudBackgroundCats`,
      {
        red: 64,
        green: 145,
        blue: 208,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuItemIcon`,
      {
        red: 141,
        green: 145,
        blue: 148,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuName`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuPhone`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 195,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuPhoneCats`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopBackgroundCats`,
      {
        red: 90,
        green: 158,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopShadow`,
      {
        red: 23,
        green: 82,
        blue: 132,
        alpha: 41,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopShadowCats`,
      {
        red: 44,
        green: 158,
        blue: 255,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage`,
      {
        red: 37,
        green: 121,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessageArchived`,
      {
        red: 145,
        green: 145,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessageArchived_threeLines`,
      {
        red: 145,
        green: 145,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage_threeLines`,
      {
        red: 66,
        green: 68,
        blue: 73,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_onlineCircle`,
      {
        red: 41,
        green: 168,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_pinnedOverlay`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 6,
      } as Color,
    ] as [string, Color],
    [
      `chats_secretIcon`,
      {
        red: 25,
        green: 177,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_secretName`,
      {
        red: 0,
        green: 166,
        blue: 14,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentCheck`,
      {
        red: 26,
        green: 159,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentClock`,
      {
        red: 150,
        green: 180,
        blue: 198,
        alpha: 123,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentError`,
      {
        red: 255,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentReadCheck`,
      {
        red: 26,
        green: 156,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_tabUnreadActiveBackground`,
      {
        red: 47,
        green: 162,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_tabUnreadUnactiveBackground`,
      {
        red: 47,
        green: 162,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_unreadCounter`,
      {
        red: 36,
        green: 174,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_verifiedBackground`,
      {
        red: 82,
        green: 173,
        blue: 248,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressInner2`,
      {
        red: 195,
        green: 221,
        blue: 246,
        alpha: 206,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressOuter1`,
      {
        red: 59,
        green: 166,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressOuter2`,
      {
        red: 69,
        green: 162,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogBadgeBackground`,
      {
        red: 44,
        green: 160,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogButton`,
      {
        red: 42,
        green: 144,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogCheckboxSquareBackground`,
      {
        red: 36,
        green: 145,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogFloatingButton`,
      {
        red: 71,
        green: 166,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgress`,
      {
        red: 34,
        green: 156,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgressBackground`,
      {
        red: 204,
        green: 229,
        blue: 249,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogProgressCircle`,
      {
        red: 68,
        green: 154,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogRadioBackgroundChecked`,
      {
        red: 37,
        green: 158,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogRoundCheckBox`,
      {
        red: 47,
        green: 170,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue`,
      {
        red: 31,
        green: 141,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue2`,
      {
        red: 30,
        green: 149,
        blue: 219,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue3`,
      {
        red: 29,
        green: 143,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue4`,
      {
        red: 17,
        green: 145,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray`,
      {
        red: 50,
        green: 154,
        blue: 221,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextLink`,
      {
        red: 37,
        green: 137,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextRed`,
      {
        red: 230,
        green: 85,
        blue: 94,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextRed2`,
      {
        red: 235,
        green: 85,
        blue: 93,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `divider`,
      {
        red: 230,
        green: 230,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `fastScrollActive`,
      {
        red: 66,
        green: 164,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `featuredStickers_addButton`,
      {
        red: 77,
        green: 160,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `featuredStickers_addedIcon`,
      {
        red: 50,
        green: 165,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `graySection`,
      {
        red: 246,
        green: 246,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_checkbox`,
      {
        red: 81,
        green: 208,
        blue: 76,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_cursor`,
      {
        red: 50,
        green: 159,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerClose`,
      {
        red: 140,
        green: 149,
        blue: 154,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerPlayPause`,
      {
        red: 30,
        green: 157,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerTitle`,
      {
        red: 38,
        green: 39,
        blue: 40,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_changephoneinfo_changeText`,
      {
        red: 55,
        green: 159,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_graySectionText`,
      {
        red: 132,
        green: 135,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `listSelector`,
      {
        red: 51,
        green: 51,
        blue: 51,
        alpha: 78,
      } as Color,
    ] as [string, Color],
    [
      `listSelectorSDK21`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 15,
      } as Color,
    ] as [string, Color],
    [
      `location_sendLocationBackground`,
      {
        red: 80,
        green: 164,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `musicPicker_buttonBackground`,
      {
        red: 69,
        green: 166,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `musicPicker_checkbox`,
      {
        red: 66,
        green: 181,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `picker_badge`,
      {
        red: 53,
        green: 163,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `picker_enabledButton`,
      {
        red: 39,
        green: 158,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_buttonActive`,
      {
        red: 44,
        green: 163,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_progress`,
      {
        red: 33,
        green: 157,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_time`,
      {
        red: 156,
        green: 164,
        blue: 176,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionBackground`,
      {
        red: 66,
        green: 168,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionPressedBackground`,
      {
        red: 42,
        green: 130,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_creatorIcon`,
      {
        red: 17,
        green: 141,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_status`,
      {
        red: 26,
        green: 150,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_title`,
      {
        red: 54,
        green: 54,
        blue: 54,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_verifiedBackground`,
      {
        red: 83,
        green: 160,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_verifiedCheck`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `progressCircle`,
      {
        red: 63,
        green: 165,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `radioBackgroundChecked`,
      {
        red: 31,
        green: 155,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `returnToCallBackground`,
      {
        red: 80,
        green: 168,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `sharedMedia_linkPlaceholder`,
      {
        red: 244,
        green: 244,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartActiveLine`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 20,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_blue`,
      {
        red: 50,
        green: 127,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_golden`,
      {
        red: 227,
        green: 183,
        blue: 39,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_green`,
      {
        red: 97,
        green: 199,
        blue: 82,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_indigo`,
      {
        red: 127,
        green: 121,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_lightblue`,
      {
        red: 88,
        green: 168,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_lightgreen`,
      {
        red: 158,
        green: 212,
        blue: 72,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_orange`,
      {
        red: 227,
        green: 183,
        blue: 39,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_red`,
      {
        red: 224,
        green: 83,
        blue: 86,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switch2Track`,
      {
        red: 245,
        green: 116,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switch2TrackChecked`,
      {
        red: 80,
        green: 167,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchThumbChecked`,
      {
        red: 22,
        green: 141,
        blue: 254,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueChecked`,
      {
        red: 0,
        green: 132,
        blue: 203,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackChecked`,
      {
        red: 60,
        green: 163,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundCheckText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlackText`,
      {
        red: 51,
        green: 51,
        blue: 51,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueButton`,
      {
        red: 32,
        green: 144,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueHeader`,
      {
        red: 37,
        green: 141,
        blue: 226,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueIcon`,
      {
        red: 69,
        green: 156,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText`,
      {
        red: 35,
        green: 138,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText3`,
      {
        red: 49,
        green: 138,
        blue: 218,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText4`,
      {
        red: 62,
        green: 150,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText5`,
      {
        red: 58,
        green: 156,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText7`,
      {
        red: 70,
        green: 157,
        blue: 225,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayIcon`,
      {
        red: 133,
        green: 136,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText`,
      {
        red: 140,
        green: 142,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGreenText2`,
      {
        red: 4,
        green: 172,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteLinkSelection`,
      {
        red: 98,
        green: 169,
        blue: 227,
        alpha: 33,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteLinkText`,
      {
        red: 50,
        green: 138,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteRedText2`,
      {
        red: 228,
        green: 69,
        blue: 82,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteValueText`,
      {
        red: 34,
        green: 147,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
  ]);

export default day;
