// This file was automatically generated by .attheme default theme
// generator, available at:
//     https://gitlab.com/snejugal/attheme-default-theme-generator

import Attheme from "..";
import { Color } from "../types";

/**
 * Generates the Default theme.
 */
const defaultTheme = () =>
  new Attheme([
    [
      `actionBarDefault`,
      {
        red: 82,
        green: 125,
        blue: 163,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchived`,
      {
        red: 118,
        green: 127,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchivedSelector`,
      {
        red: 90,
        green: 104,
        blue: 112,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSelector`,
      {
        red: 61,
        green: 107,
        blue: 150,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubtitle`,
      {
        red: 211,
        green: 225,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabSelector`,
      {
        red: 64,
        green: 111,
        blue: 156,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarWhiteSelector`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 16,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorBlue`,
      {
        red: 71,
        green: 126,
        blue: 169,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundArchived`,
      {
        red: 179,
        green: 187,
        blue: 193,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundArchivedHidden`,
      {
        red: 90,
        green: 181,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundSaved`,
      {
        red: 96,
        green: 184,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageBlue`,
      {
        red: 32,
        green: 141,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageCyan`,
      {
        red: 47,
        green: 163,
        blue: 201,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessagePink`,
      {
        red: 210,
        green: 104,
        blue: 149,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageViolet`,
      {
        red: 128,
        green: 109,
        blue: 207,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `calls_callReceivedGreenIcon`,
      {
        red: 65,
        green: 162,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_addContact`,
      {
        red: 45,
        green: 150,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_adminText`,
      {
        red: 161,
        green: 170,
        blue: 179,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachAudioText`,
      {
        red: 222,
        green: 71,
        blue: 71,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachContactText`,
      {
        red: 223,
        green: 160,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachFileText`,
      {
        red: 20,
        green: 168,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachGalleryText`,
      {
        red: 46,
        green: 141,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachHideBackground`,
      {
        red: 181,
        green: 190,
        blue: 204,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachLocationText`,
      {
        red: 60,
        green: 171,
        blue: 47,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachPollText`,
      {
        red: 223,
        green: 160,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbarFill`,
      {
        red: 94,
        green: 171,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioTitleText`,
      {
        red: 26,
        green: 46,
        blue: 59,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubbleSelected`,
      {
        red: 232,
        green: 245,
        blue: 252,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactBackground`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactNameText`,
      {
        red: 17,
        green: 35,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneSelectedText`,
      {
        red: 137,
        green: 180,
        blue: 193,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneText`,
      {
        red: 161,
        green: 170,
        blue: 179,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileNameText`,
      {
        red: 17,
        green: 35,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileProgress`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inForwardedNameText`,
      {
        red: 8,
        green: 126,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstant`,
      {
        red: 31,
        green: 149,
        blue: 226,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstantSelected`,
      {
        red: 31,
        green: 149,
        blue: 226,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoader`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderSelected`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantSelectedText`,
      {
        red: 58,
        green: 140,
        blue: 207,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantText`,
      {
        red: 35,
        green: 145,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewLine`,
      {
        red: 55,
        green: 163,
        blue: 239,
        alpha: 235,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyLine`,
      {
        red: 53,
        green: 157,
        blue: 230,
        alpha: 235,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyNameText`,
      {
        red: 32,
        green: 141,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSentClockSelected`,
      {
        red: 137,
        green: 180,
        blue: 193,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSiteNameText`,
      {
        red: 21,
        green: 133,
        blue: 208,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViaBotNameText`,
      {
        red: 50,
        green: 138,
        blue: 207,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViewsSelected`,
      {
        red: 137,
        green: 180,
        blue: 193,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbarFill`,
      {
        red: 80,
        green: 175,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkIn`,
      {
        red: 10,
        green: 121,
        blue: 189,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkOut`,
      {
        red: 9,
        green: 123,
        blue: 195,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelVoiceBackground`,
      {
        red: 97,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioCacheSeekbar`,
      {
        red: 167,
        green: 204,
        blue: 231,
        alpha: 194,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationSelectedText`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationText`,
      {
        red: 140,
        green: 170,
        blue: 189,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioProgress`,
      {
        red: 160,
        green: 202,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbar`,
      {
        red: 167,
        green: 204,
        blue: 231,
        alpha: 137,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarFill`,
      {
        red: 69,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarSelected`,
      {
        red: 83,
        green: 171,
        blue: 221,
        alpha: 71,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSelectedProgress`,
      {
        red: 141,
        green: 201,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioTitleText`,
      {
        red: 24,
        green: 44,
        blue: 56,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubble`,
      {
        red: 230,
        green: 242,
        blue: 252,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleSelected`,
      {
        red: 214,
        green: 242,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleShadow`,
      {
        red: 1,
        green: 48,
        blue: 74,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactBackground`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactNameText`,
      {
        red: 30,
        green: 47,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneSelectedText`,
      {
        red: 107,
        green: 152,
        blue: 188,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneText`,
      {
        red: 124,
        green: 150,
        blue: 167,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackground`,
      {
        red: 199,
        green: 226,
        blue: 247,
        alpha: 178,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackgroundSelected`,
      {
        red: 187,
        green: 229,
        blue: 252,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileIcon`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoSelectedText`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoText`,
      {
        red: 134,
        green: 162,
        blue: 180,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileNameText`,
      {
        red: 30,
        green: 47,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgress`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgressSelected`,
      {
        red: 209,
        green: 241,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileSelectedIcon`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outForwardedNameText`,
      {
        red: 34,
        green: 132,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstant`,
      {
        red: 8,
        green: 146,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstantSelected`,
      {
        red: 30,
        green: 156,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoader`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhoto`,
      {
        red: 69,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIcon`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIconSelected`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoSelected`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderSelected`,
      {
        red: 68,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationBackground`,
      {
        red: 199,
        green: 226,
        blue: 246,
        alpha: 196,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationIcon`,
      {
        red: 124,
        green: 160,
        blue: 193,
        alpha: 130,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMediaIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenu`,
      {
        red: 168,
        green: 196,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenuSelected`,
      {
        red: 148,
        green: 198,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantSelectedText`,
      {
        red: 34,
        green: 132,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantText`,
      {
        red: 34,
        green: 132,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewLine`,
      {
        red: 67,
        green: 166,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyLine`,
      {
        red: 55,
        green: 154,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageSelectedText`,
      {
        red: 123,
        green: 163,
        blue: 203,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageText`,
      {
        red: 140,
        green: 170,
        blue: 189,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyNameText`,
      {
        red: 36,
        green: 137,
        blue: 206,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheck`,
      {
        red: 27,
        green: 155,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheckRead`,
      {
        red: 27,
        green: 155,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheckSelected`,
      {
        red: 27,
        green: 153,
        blue: 226,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClock`,
      {
        red: 140,
        green: 170,
        blue: 189,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClockSelected`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSiteNameText`,
      {
        red: 34,
        green: 130,
        blue: 201,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeSelectedText`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeText`,
      {
        red: 140,
        green: 170,
        blue: 189,
        alpha: 247,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoSelectedText`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoText`,
      {
        red: 130,
        green: 158,
        blue: 175,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViaBotNameText`,
      {
        red: 34,
        green: 132,
        blue: 202,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViews`,
      {
        red: 140,
        green: 170,
        blue: 189,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViewsSelected`,
      {
        red: 123,
        green: 163,
        blue: 202,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbar`,
      {
        red: 164,
        green: 196,
        blue: 223,
        alpha: 189,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarFill`,
      {
        red: 69,
        green: 169,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarSelected`,
      {
        red: 106,
        green: 171,
        blue: 211,
        alpha: 121,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelIcons`,
      {
        red: 73,
        green: 161,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelName`,
      {
        red: 51,
        green: 145,
        blue: 222,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_searchPanelIcons`,
      {
        red: 58,
        green: 151,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_searchPanelText`,
      {
        red: 63,
        green: 153,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_selectedBackground`,
      {
        red: 7,
        green: 122,
        blue: 196,
        alpha: 50,
      } as Color,
    ] as [string, Color],
    [
      `chat_status`,
      {
        red: 215,
        green: 231,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelLine`,
      {
        red: 73,
        green: 168,
        blue: 228,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelTitle`,
      {
        red: 54,
        green: 150,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartText`,
      {
        red: 67,
        green: 147,
        blue: 221,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_wallpaper`,
      {
        red: 83,
        green: 144,
        blue: 209,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_wallpaper_gradient_to`,
      {
        red: 171,
        green: 200,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionBackground`,
      {
        red: 97,
        green: 170,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionMessage`,
      {
        red: 29,
        green: 127,
        blue: 191,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionPressedBackground`,
      {
        red: 85,
        green: 155,
        blue: 212,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_attachMessage`,
      {
        red: 29,
        green: 128,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuItemIcon`,
      {
        red: 142,
        green: 148,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuItemText`,
      {
        red: 63,
        green: 63,
        blue: 63,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuPhoneCats`,
      {
        red: 215,
        green: 236,
        blue: 249,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopBackgroundCats`,
      {
        red: 89,
        green: 148,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopShadow`,
      {
        red: 25,
        green: 73,
        blue: 113,
        alpha: 77,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage`,
      {
        red: 29,
        green: 128,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessageArchived`,
      {
        red: 145,
        green: 145,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage_threeLines`,
      {
        red: 29,
        green: 128,
        blue: 193,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_onlineCircle`,
      {
        red: 54,
        green: 176,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentCheck`,
      {
        red: 15,
        green: 157,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentClock`,
      {
        red: 184,
        green: 188,
        blue: 191,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentReadCheck`,
      {
        red: 15,
        green: 156,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_unreadCounter`,
      {
        red: 41,
        green: 174,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_verifiedBackground`,
      {
        red: 50,
        green: 161,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressOuter1`,
      {
        red: 61,
        green: 159,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogBadgeBackground`,
      {
        red: 55,
        green: 176,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogButton`,
      {
        red: 54,
        green: 145,
        blue: 217,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgress`,
      {
        red: 71,
        green: 157,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgressBackground`,
      {
        red: 224,
        green: 239,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue`,
      {
        red: 34,
        green: 148,
        blue: 217,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue2`,
      {
        red: 34,
        green: 148,
        blue: 217,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue3`,
      {
        red: 22,
        green: 159,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue4`,
      {
        red: 22,
        green: 159,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray2`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray3`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray4`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextLink`,
      {
        red: 41,
        green: 129,
        blue: 196,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `emptyListPlaceholder`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `featuredStickers_addButtonPressed`,
      {
        red: 66,
        green: 153,
        blue: 219,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `graySection`,
      {
        red: 246,
        green: 246,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerPlayPause`,
      {
        red: 67,
        green: 170,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_graySectionText`,
      {
        red: 137,
        green: 140,
        blue: 142,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `listSelectorSDK21`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 13,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionPressedBackground`,
      {
        red: 229,
        green: 229,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `progressCircle`,
      {
        red: 36,
        green: 166,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartActiveLine`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 20,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_blue`,
      {
        red: 50,
        green: 127,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_golden`,
      {
        red: 227,
        green: 183,
        blue: 39,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_green`,
      {
        red: 97,
        green: 199,
        blue: 82,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_indigo`,
      {
        red: 127,
        green: 121,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_lightblue`,
      {
        red: 88,
        green: 168,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_lightgreen`,
      {
        red: 143,
        green: 207,
        blue: 57,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_orange`,
      {
        red: 227,
        green: 183,
        blue: 39,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `statisticChartLine_red`,
      {
        red: 224,
        green: 83,
        blue: 86,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackChecked`,
      {
        red: 81,
        green: 171,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueHeader`,
      {
        red: 36,
        green: 146,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText`,
      {
        red: 7,
        green: 127,
        blue: 200,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText2`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText3`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText4`,
      {
        red: 140,
        green: 143,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText6`,
      {
        red: 123,
        green: 126,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteLinkText`,
      {
        red: 42,
        green: 132,
        blue: 200,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteValueText`,
      {
        red: 57,
        green: 148,
        blue: 211,
        alpha: 255,
      } as Color,
    ] as [string, Color],
  ]);

export default defaultTheme;
