// This file was automatically generated by .attheme default theme
// generator, available at:
//     https://gitlab.com/snejugal/attheme-default-theme-generator

import Attheme from "..";
import { Color } from "../types";

/**
 * Generates the Graphite theme.
 */
const graphite = () =>
  new Attheme([
    [
      `actionBarActionModeDefault`,
      {
        red: 60,
        green: 63,
        blue: 70,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarActionModeDefaultIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarActionModeDefaultSelector`,
      {
        red: 77,
        green: 85,
        blue: 89,
        alpha: 122,
      } as Color,
    ] as [string, Color],
    [
      `actionBarActionModeDefaultTop`,
      {
        red: 61,
        green: 64,
        blue: 72,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefault`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultArchived`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSearchPlaceholder`,
      {
        red: 128,
        green: 135,
        blue: 147,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSelector`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubmenuBackground`,
      {
        red: 64,
        green: 67,
        blue: 75,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubmenuItem`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubmenuItemIcon`,
      {
        red: 136,
        green: 147,
        blue: 156,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarDefaultSubtitle`,
      {
        red: 131,
        green: 137,
        blue: 143,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabActiveText`,
      {
        red: 136,
        green: 187,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `actionBarTabLine`,
      {
        red: 121,
        green: 172,
        blue: 255,
        alpha: 236,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorBlue`,
      {
        red: 73,
        green: 80,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorCyan`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorGreen`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorOrange`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorPink`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorRed`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_actionBarSelectorViolet`,
      {
        red: 73,
        green: 81,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarBlue`,
      {
        red: 52,
        green: 55,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarCyan`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarGreen`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarOrange`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarPink`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarRed`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundActionBarViolet`,
      {
        red: 33,
        green: 36,
        blue: 38,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundArchived`,
      {
        red: 74,
        green: 78,
        blue: 86,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundArchivedHidden`,
      {
        red: 66,
        green: 71,
        blue: 79,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundBlue`,
      {
        red: 128,
        green: 158,
        blue: 221,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundCyan`,
      {
        red: 101,
        green: 182,
        blue: 204,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundGreen`,
      {
        red: 127,
        green: 193,
        blue: 116,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundGroupCreateSpanBlue`,
      {
        red: 94,
        green: 129,
        blue: 173,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundInProfileBlue`,
      {
        red: 117,
        green: 159,
        blue: 221,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundOrange`,
      {
        red: 242,
        green: 186,
        blue: 107,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_backgroundSaved`,
      {
        red: 116,
        green: 156,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageBlue`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageCyan`,
      {
        red: 129,
        green: 203,
        blue: 220,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageGreen`,
      {
        red: 147,
        green: 217,
        blue: 136,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageOrange`,
      {
        red: 236,
        green: 175,
        blue: 108,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessagePink`,
      {
        red: 237,
        green: 116,
        blue: 164,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageRed`,
      {
        red: 239,
        green: 115,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_nameInMessageViolet`,
      {
        red: 165,
        green: 149,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileBlue`,
      {
        red: 130,
        green: 134,
        blue: 142,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileCyan`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileGreen`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileOrange`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfilePink`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileRed`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `avatar_subtitleInProfileViolet`,
      {
        red: 138,
        green: 138,
        blue: 138,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `calls_callReceivedGreenIcon`,
      {
        red: 140,
        green: 242,
        blue: 142,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `calls_callReceivedRedIcon`,
      {
        red: 243,
        green: 99,
        blue: 112,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `changephoneinfo_image`,
      {
        red: 91,
        green: 103,
        blue: 112,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_addContact`,
      {
        red: 108,
        green: 162,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_adminSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachAudioBackground`,
      {
        red: 236,
        green: 169,
        blue: 80,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachCameraIcon1`,
      {
        red: 255,
        green: 157,
        blue: 99,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachCameraIcon2`,
      {
        red: 235,
        green: 117,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachCameraIcon3`,
      {
        red: 104,
        green: 182,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachCameraIcon4`,
      {
        red: 136,
        green: 148,
        blue: 225,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachCameraIcon5`,
      {
        red: 102,
        green: 217,
        blue: 123,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachContactBackground`,
      {
        red: 108,
        green: 181,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachFileBackground`,
      {
        red: 116,
        green: 156,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachGalleryBackground`,
      {
        red: 132,
        green: 161,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachHideBackground`,
      {
        red: 68,
        green: 73,
        blue: 81,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachLocationBackground`,
      {
        red: 107,
        green: 203,
        blue: 125,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachSendBackground`,
      {
        red: 118,
        green: 167,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_attachVideoBackground`,
      {
        red: 231,
        green: 102,
        blue: 106,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botKeyboardButtonBackground`,
      {
        red: 35,
        green: 40,
        blue: 43,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botKeyboardButtonBackgroundPressed`,
      {
        red: 48,
        green: 55,
        blue: 59,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botKeyboardButtonText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_botSwitchToInlineText`,
      {
        red: 141,
        green: 179,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_editDoneIcon`,
      {
        red: 111,
        green: 179,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelBackground`,
      {
        red: 42,
        green: 48,
        blue: 52,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelBackspace`,
      {
        red: 96,
        green: 106,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelBadgeBackground`,
      {
        red: 129,
        green: 186,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelEmptyText`,
      {
        red: 80,
        green: 89,
        blue: 98,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelIcon`,
      {
        red: 96,
        green: 106,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelIconSelected`,
      {
        red: 123,
        green: 178,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelIconSelector`,
      {
        red: 106,
        green: 177,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelNewTrending`,
      {
        red: 124,
        green: 178,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelShadowLine`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelStickerPackSelector`,
      {
        red: 250,
        green: 254,
        blue: 255,
        alpha: 12,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelStickerPackSelectorLine`,
      {
        red: 125,
        green: 174,
        blue: 243,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelStickerSetNameHighlight`,
      {
        red: 122,
        green: 175,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelTrendingDescription`,
      {
        red: 102,
        green: 107,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_emojiPanelTrendingTitle`,
      {
        red: 222,
        green: 235,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_fieldOverlayText`,
      {
        red: 135,
        green: 180,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_goDownButton`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_goDownButtonCounterBackground`,
      {
        red: 118,
        green: 174,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_goDownButtonIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 229,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioDurationSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioDurationText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioPerfomerSelectedText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioPerfomerText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioProgress`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbar`,
      {
        red: 88,
        green: 91,
        blue: 100,
        alpha: 221,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbarFill`,
      {
        red: 127,
        green: 170,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSeekbarSelected`,
      {
        red: 132,
        green: 181,
        blue: 238,
        alpha: 50,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioSelectedProgress`,
      {
        red: 52,
        green: 69,
        blue: 99,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inAudioTitleText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubble`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubbleSelected`,
      {
        red: 65,
        green: 78,
        blue: 106,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inBubbleShadow`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactBackground`,
      {
        red: 123,
        green: 168,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneSelectedText`,
      {
        red: 130,
        green: 151,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inContactPhoneText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileBackground`,
      {
        red: 70,
        green: 75,
        blue: 84,
        alpha: 143,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileBackgroundSelected`,
      {
        red: 74,
        green: 91,
        blue: 127,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileIcon`,
      {
        red: 43,
        green: 51,
        blue: 57,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileInfoSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileInfoText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 250,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileProgress`,
      {
        red: 93,
        green: 111,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileProgressSelected`,
      {
        red: 166,
        green: 207,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inFileSelectedIcon`,
      {
        red: 26,
        green: 64,
        blue: 99,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inForwardedNameText`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstant`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inInstantSelected`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoader`,
      {
        red: 121,
        green: 168,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderPhoto`,
      {
        red: 36,
        green: 52,
        blue: 66,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderPhotoIcon`,
      {
        red: 89,
        green: 111,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderPhotoIconSelected`,
      {
        red: 169,
        green: 207,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderPhotoSelected`,
      {
        red: 28,
        green: 64,
        blue: 99,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLoaderSelected`,
      {
        red: 117,
        green: 171,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inLocationBackground`,
      {
        red: 71,
        green: 82,
        blue: 100,
        alpha: 111,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMediaIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMediaIconSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMenu`,
      {
        red: 145,
        green: 161,
        blue: 179,
        alpha: 122,
      } as Color,
    ] as [string, Color],
    [
      `chat_inMenuSelected`,
      {
        red: 169,
        green: 207,
        blue: 238,
        alpha: 130,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantSelectedText`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewInstantText`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inPreviewLine`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyLine`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyMediaMessageSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyMediaMessageText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyMessageText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_inReplyNameText`,
      {
        red: 136,
        green: 180,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSentClock`,
      {
        red: 128,
        green: 145,
        blue: 160,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSentClockSelected`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_inSiteNameText`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inTimeSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inTimeText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 217,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVenueInfoSelectedText`,
      {
        red: 132,
        green: 160,
        blue: 184,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVenueInfoText`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 207,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViaBotNameText`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViews`,
      {
        red: 142,
        green: 143,
        blue: 152,
        alpha: 180,
      } as Color,
    ] as [string, Color],
    [
      `chat_inViewsSelected`,
      {
        red: 160,
        green: 186,
        blue: 216,
        alpha: 182,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbar`,
      {
        red: 113,
        green: 119,
        blue: 134,
        alpha: 149,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbarFill`,
      {
        red: 123,
        green: 172,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_inVoiceSeekbarSelected`,
      {
        red: 118,
        green: 152,
        blue: 184,
        alpha: 150,
      } as Color,
    ] as [string, Color],
    [
      `chat_inlineResultIcon`,
      {
        red: 133,
        green: 176,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_linkSelectBackground`,
      {
        red: 127,
        green: 167,
        blue: 236,
        alpha: 56,
      } as Color,
    ] as [string, Color],
    [
      `chat_mediaLoaderPhotoIconSelected`,
      {
        red: 227,
        green: 227,
        blue: 227,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_mediaMenu`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkIn`,
      {
        red: 131,
        green: 176,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageLinkOut`,
      {
        red: 178,
        green: 215,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelBackground`,
      {
        red: 49,
        green: 54,
        blue: 59,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelCancelInlineBot`,
      {
        red: 100,
        green: 112,
        blue: 119,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelHint`,
      {
        red: 96,
        green: 102,
        blue: 109,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelIcons`,
      {
        red: 100,
        green: 112,
        blue: 119,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelSend`,
      {
        red: 121,
        green: 173,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelShadow`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelVoiceBackground`,
      {
        red: 116,
        green: 168,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messagePanelVoiceDelete`,
      {
        red: 103,
        green: 115,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageTextIn`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_messageTextOut`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_muteIcon`,
      {
        red: 94,
        green: 103,
        blue: 109,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioCacheSeekbar`,
      {
        red: 99,
        green: 141,
        blue: 185,
        alpha: 183,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationSelectedText`,
      {
        red: 155,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioDurationText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioPerfomerSelectedText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioPerfomerText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioProgress`,
      {
        red: 77,
        green: 105,
        blue: 143,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbar`,
      {
        red: 192,
        green: 225,
        blue: 255,
        alpha: 58,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarFill`,
      {
        red: 141,
        green: 197,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSeekbarSelected`,
      {
        red: 142,
        green: 186,
        blue: 228,
        alpha: 67,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioSelectedProgress`,
      {
        red: 104,
        green: 143,
        blue: 203,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outAudioTitleText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubble`,
      {
        red: 85,
        green: 115,
        blue: 167,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleSelected`,
      {
        red: 95,
        green: 135,
        blue: 198,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outBubbleShadow`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactBackground`,
      {
        red: 121,
        green: 168,
        blue: 234,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneSelectedText`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outContactPhoneText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackground`,
      {
        red: 98,
        green: 133,
        blue: 182,
        alpha: 182,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileBackgroundSelected`,
      {
        red: 112,
        green: 152,
        blue: 208,
        alpha: 158,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileIcon`,
      {
        red: 69,
        green: 101,
        blue: 156,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoSelectedText`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileInfoText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileNameText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgress`,
      {
        red: 114,
        green: 165,
        blue: 208,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileProgressSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outFileSelectedIcon`,
      {
        red: 101,
        green: 145,
        blue: 203,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outForwardedNameText`,
      {
        red: 171,
        green: 216,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstant`,
      {
        red: 164,
        green: 204,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outInstantSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoader`,
      {
        red: 124,
        green: 171,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhoto`,
      {
        red: 85,
        green: 122,
        blue: 176,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIcon`,
      {
        red: 119,
        green: 152,
        blue: 208,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoIconSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderPhotoSelected`,
      {
        red: 87,
        green: 126,
        blue: 172,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLoaderSelected`,
      {
        red: 124,
        green: 171,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationBackground`,
      {
        red: 91,
        green: 126,
        blue: 167,
        alpha: 151,
      } as Color,
    ] as [string, Color],
    [
      `chat_outLocationIcon`,
      {
        red: 171,
        green: 206,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMediaIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMediaIconSelected`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenu`,
      {
        red: 126,
        green: 158,
        blue: 194,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outMenuSelected`,
      {
        red: 158,
        green: 197,
        blue: 236,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantSelectedText`,
      {
        red: 171,
        green: 216,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewInstantText`,
      {
        red: 176,
        green: 212,
        blue: 248,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outPreviewLine`,
      {
        red: 171,
        green: 216,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyLine`,
      {
        red: 135,
        green: 188,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageSelectedText`,
      {
        red: 171,
        green: 216,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMediaMessageText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 220,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyMessageText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 240,
      } as Color,
    ] as [string, Color],
    [
      `chat_outReplyNameText`,
      {
        red: 156,
        green: 201,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheck`,
      {
        red: 152,
        green: 198,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentCheckSelected`,
      {
        red: 146,
        green: 205,
        blue: 252,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClock`,
      {
        red: 146,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSentClockSelected`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outSiteNameText`,
      {
        red: 181,
        green: 217,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeSelectedText`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outTimeText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoSelectedText`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueInfoText`,
      {
        red: 149,
        green: 184,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVenueNameText`,
      {
        red: 209,
        green: 235,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViaBotNameText`,
      {
        red: 171,
        green: 216,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViews`,
      {
        red: 152,
        green: 183,
        blue: 226,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outViewsSelected`,
      {
        red: 152,
        green: 201,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbar`,
      {
        red: 154,
        green: 191,
        blue: 232,
        alpha: 99,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarFill`,
      {
        red: 163,
        green: 199,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_outVoiceSeekbarSelected`,
      {
        red: 185,
        green: 215,
        blue: 255,
        alpha: 110,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordTime`,
      {
        red: 119,
        green: 130,
        blue: 137,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordVoiceCancel`,
      {
        red: 126,
        green: 138,
        blue: 146,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordedVoiceBackground`,
      {
        red: 123,
        green: 168,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_recordedVoiceDot`,
      {
        red: 226,
        green: 89,
        blue: 80,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelClose`,
      {
        red: 100,
        green: 112,
        blue: 119,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelIcons`,
      {
        red: 132,
        green: 180,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelLine`,
      {
        red: 29,
        green: 29,
        blue: 29,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelMessage`,
      {
        red: 123,
        green: 137,
        blue: 147,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_replyPanelName`,
      {
        red: 113,
        green: 167,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_reportSpam`,
      {
        red: 224,
        green: 96,
        blue: 93,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_searchPanelIcons`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 222,
      } as Color,
    ] as [string, Color],
    [
      `chat_searchPanelText`,
      {
        red: 137,
        green: 180,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_secretChatStatusText`,
      {
        red: 103,
        green: 113,
        blue: 127,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_secretTimeText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_secretTimerBackground`,
      {
        red: 30,
        green: 30,
        blue: 30,
        alpha: 182,
      } as Color,
    ] as [string, Color],
    [
      `chat_selectedBackground`,
      {
        red: 115,
        green: 172,
        blue: 255,
        alpha: 30,
      } as Color,
    ] as [string, Color],
    [
      `chat_sentError`,
      {
        red: 232,
        green: 83,
        blue: 90,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceBackground`,
      {
        red: 57,
        green: 60,
        blue: 66,
        alpha: 140,
      } as Color,
    ] as [string, Color],
    [
      `chat_serviceBackgroundSelected`,
      {
        red: 72,
        green: 85,
        blue: 108,
        alpha: 117,
      } as Color,
    ] as [string, Color],
    [
      `chat_status`,
      {
        red: 129,
        green: 186,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_textSelectBackground`,
      {
        red: 130,
        green: 169,
        blue: 230,
        alpha: 87,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelBackground`,
      {
        red: 34,
        green: 37,
        blue: 39,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelClose`,
      {
        red: 79,
        green: 89,
        blue: 100,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelLine`,
      {
        red: 128,
        green: 180,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelMessage`,
      {
        red: 101,
        green: 117,
        blue: 125,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_topPanelTitle`,
      {
        red: 133,
        green: 182,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartArrowIcon`,
      {
        red: 101,
        green: 108,
        blue: 131,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartBackground`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chat_unreadMessagesStartText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 218,
      } as Color,
    ] as [string, Color],
    [
      `chat_wallpaper`,
      {
        red: 38,
        green: 43,
        blue: 47,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionBackground`,
      {
        red: 131,
        green: 167,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionMessage`,
      {
        red: 124,
        green: 169,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_actionPressedBackground`,
      {
        red: 139,
        green: 189,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_archiveBackground`,
      {
        red: 118,
        green: 154,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_archivePinBackground`,
      {
        red: 45,
        green: 47,
        blue: 52,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_attachMessage`,
      {
        red: 127,
        green: 136,
        blue: 144,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_date`,
      {
        red: 118,
        green: 127,
        blue: 134,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_draft`,
      {
        red: 232,
        green: 108,
        blue: 108,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuBackground`,
      {
        red: 48,
        green: 51,
        blue: 59,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuCloudBackgroundCats`,
      {
        red: 120,
        green: 158,
        blue: 216,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuItemIcon`,
      {
        red: 110,
        green: 119,
        blue: 134,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuItemText`,
      {
        red: 240,
        green: 240,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuPhone`,
      {
        red: 226,
        green: 242,
        blue: 255,
        alpha: 112,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuPhoneCats`,
      {
        red: 161,
        green: 191,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_menuTopShadow`,
      {
        red: 27,
        green: 27,
        blue: 27,
        alpha: 63,
      } as Color,
    ] as [string, Color],
    [
      `chats_message`,
      {
        red: 127,
        green: 137,
        blue: 144,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_messageArchived`,
      {
        red: 127,
        green: 137,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_muteIcon`,
      {
        red: 96,
        green: 104,
        blue: 111,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_name`,
      {
        red: 245,
        green: 245,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameArchived`,
      {
        red: 245,
        green: 245,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 238,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage`,
      {
        red: 124,
        green: 169,
        blue: 224,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessageArchived`,
      {
        red: 128,
        green: 138,
        blue: 145,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessageArchived_threeLines`,
      {
        red: 230,
        green: 230,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_nameMessage_threeLines`,
      {
        red: 230,
        green: 230,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_onlineCircle`,
      {
        red: 110,
        green: 211,
        blue: 120,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_pinnedIcon`,
      {
        red: 100,
        green: 110,
        blue: 117,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_pinnedOverlay`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 24,
      } as Color,
    ] as [string, Color],
    [
      `chats_secretIcon`,
      {
        red: 105,
        green: 227,
        blue: 141,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_secretName`,
      {
        red: 117,
        green: 226,
        blue: 144,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentCheck`,
      {
        red: 112,
        green: 206,
        blue: 143,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentClock`,
      {
        red: 122,
        green: 160,
        blue: 203,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_sentError`,
      {
        red: 228,
        green: 105,
        blue: 114,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_tabletSelectedOverlay`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 15,
      } as Color,
    ] as [string, Color],
    [
      `chats_unreadCounter`,
      {
        red: 121,
        green: 173,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_unreadCounterMuted`,
      {
        red: 80,
        green: 83,
        blue: 91,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `chats_verifiedBackground`,
      {
        red: 115,
        green: 170,
        blue: 238,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `checkbox`,
      {
        red: 101,
        green: 192,
        blue: 127,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `checkboxSquareBackground`,
      {
        red: 124,
        green: 165,
        blue: 223,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressInner1`,
      {
        red: 186,
        green: 215,
        blue: 246,
        alpha: 47,
      } as Color,
    ] as [string, Color],
    [
      `contextProgressOuter1`,
      {
        red: 130,
        green: 181,
        blue: 248,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogBackground`,
      {
        red: 53,
        green: 56,
        blue: 63,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogBackgroundGray`,
      {
        red: 48,
        green: 50,
        blue: 57,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogBadgeBackground`,
      {
        red: 124,
        green: 173,
        blue: 249,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogButton`,
      {
        red: 130,
        green: 181,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogButtonSelector`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 20,
      } as Color,
    ] as [string, Color],
    [
      `dialogCheckboxSquareBackground`,
      {
        red: 135,
        green: 172,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogCheckboxSquareDisabled`,
      {
        red: 76,
        green: 86,
        blue: 91,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogCheckboxSquareUnchecked`,
      {
        red: 102,
        green: 110,
        blue: 115,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogFloatingButton`,
      {
        red: 124,
        green: 173,
        blue: 249,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogGrayLine`,
      {
        red: 52,
        green: 56,
        blue: 60,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogIcon`,
      {
        red: 122,
        green: 132,
        blue: 141,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogInputField`,
      {
        red: 84,
        green: 94,
        blue: 101,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogInputFieldActivated`,
      {
        red: 133,
        green: 173,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgress`,
      {
        red: 131,
        green: 179,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLineProgressBackground`,
      {
        red: 94,
        green: 104,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogLinkSelection`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 51,
      } as Color,
    ] as [string, Color],
    [
      `dialogProgressCircle`,
      {
        red: 142,
        green: 185,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogRadioBackground`,
      {
        red: 94,
        green: 105,
        blue: 115,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogRadioBackgroundChecked`,
      {
        red: 126,
        green: 166,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogRedIcon`,
      {
        red: 242,
        green: 99,
        blue: 102,
        alpha: 230,
      } as Color,
    ] as [string, Color],
    [
      `dialogRoundCheckBox`,
      {
        red: 115,
        green: 163,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogScrollGlow`,
      {
        red: 229,
        green: 239,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogSearchBackground`,
      {
        red: 60,
        green: 64,
        blue: 72,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogSearchHint`,
      {
        red: 129,
        green: 135,
        blue: 141,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogSearchIcon`,
      {
        red: 121,
        green: 126,
        blue: 131,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogSearchText`,
      {
        red: 244,
        green: 244,
        blue: 244,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogShadowLine`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 59,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlack`,
      {
        red: 250,
        green: 250,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue2`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue3`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextBlue4`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray`,
      {
        red: 135,
        green: 145,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray2`,
      {
        red: 135,
        green: 145,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray3`,
      {
        red: 135,
        green: 145,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextGray4`,
      {
        red: 135,
        green: 145,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextHint`,
      {
        red: 135,
        green: 145,
        blue: 153,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextLink`,
      {
        red: 133,
        green: 178,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextRed`,
      {
        red: 242,
        green: 99,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `dialogTextRed2`,
      {
        red: 242,
        green: 99,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `divider`,
      {
        red: 35,
        green: 35,
        blue: 35,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `emptyListPlaceholder`,
      {
        red: 84,
        green: 95,
        blue: 104,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `fastScrollActive`,
      {
        red: 121,
        green: 165,
        blue: 236,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `fastScrollInactive`,
      {
        red: 71,
        green: 79,
        blue: 86,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `featuredStickers_addedIcon`,
      {
        red: 119,
        green: 169,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `files_folderIcon`,
      {
        red: 101,
        green: 113,
        blue: 127,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `files_folderIconBackground`,
      {
        red: 43,
        green: 46,
        blue: 52,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `graySection`,
      {
        red: 48,
        green: 49,
        blue: 54,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_checkbox`,
      {
        red: 81,
        green: 194,
        blue: 124,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_checkboxCheck`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_cursor`,
      {
        red: 122,
        green: 176,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_hintText`,
      {
        red: 106,
        green: 112,
        blue: 118,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_spanBackground`,
      {
        red: 70,
        green: 75,
        blue: 84,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `groupcreate_spanText`,
      {
        red: 245,
        green: 245,
        blue: 245,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerBackground`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerClose`,
      {
        red: 95,
        green: 102,
        blue: 109,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerPerformer`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerPlayPause`,
      {
        red: 122,
        green: 171,
        blue: 235,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `inappPlayerTitle`,
      {
        red: 114,
        green: 122,
        blue: 130,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_changephoneinfo_changeText`,
      {
        red: 122,
        green: 164,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_chat_messagePanelVoiceLock`,
      {
        red: 185,
        green: 199,
        blue: 216,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_chat_messagePanelVoiceLockBackground`,
      {
        red: 47,
        green: 53,
        blue: 57,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_chats_menuTopShadow`,
      {
        red: 12,
        green: 12,
        blue: 12,
        alpha: 0,
      } as Color,
    ] as [string, Color],
    [
      `key_graySectionText`,
      {
        red: 133,
        green: 144,
        blue: 152,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_player_progressCachedBackground`,
      {
        red: 66,
        green: 72,
        blue: 78,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `key_sheet_other`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 44,
      } as Color,
    ] as [string, Color],
    [
      `key_sheet_scrollUp`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 35,
      } as Color,
    ] as [string, Color],
    [
      `listSelector`,
      {
        red: 0,
        green: 0,
        blue: 0,
        alpha: 46,
      } as Color,
    ] as [string, Color],
    [
      `listSelectorSDK21`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 15,
      } as Color,
    ] as [string, Color],
    [
      `location_markerX`,
      {
        red: 93,
        green: 111,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `musicPicker_buttonBackground`,
      {
        red: 87,
        green: 157,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `musicPicker_checkbox`,
      {
        red: 78,
        green: 170,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `passport_authorizeBackground`,
      {
        red: 90,
        green: 150,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `passport_authorizeBackgroundSelected`,
      {
        red: 109,
        green: 169,
        blue: 233,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `picker_badge`,
      {
        red: 94,
        green: 168,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `picker_disabledButton`,
      {
        red: 95,
        green: 104,
        blue: 114,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `picker_enabledButton`,
      {
        red: 97,
        green: 173,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBar`,
      {
        red: 36,
        green: 39,
        blue: 40,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBarItems`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBarSelector`,
      {
        red: 36,
        green: 39,
        blue: 40,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBarSubtitle`,
      {
        red: 113,
        green: 125,
        blue: 130,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBarTitle`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_actionBarTop`,
      {
        red: 28,
        green: 31,
        blue: 32,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_background`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_button`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_buttonActive`,
      {
        red: 123,
        green: 171,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_placeholder`,
      {
        red: 29,
        green: 32,
        blue: 35,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_placeholderBackground`,
      {
        red: 57,
        green: 63,
        blue: 67,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_progress`,
      {
        red: 135,
        green: 171,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_progressBackground`,
      {
        red: 79,
        green: 87,
        blue: 93,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `player_seekBarBackground`,
      {
        red: 82,
        green: 82,
        blue: 82,
        alpha: 71,
      } as Color,
    ] as [string, Color],
    [
      `player_time`,
      {
        red: 125,
        green: 135,
        blue: 139,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionBackground`,
      {
        red: 120,
        green: 151,
        blue: 214,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionIcon`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_actionPressedBackground`,
      {
        red: 142,
        green: 177,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_creatorIcon`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_status`,
      {
        red: 129,
        green: 186,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_verifiedBackground`,
      {
        red: 130,
        green: 176,
        blue: 242,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `profile_verifiedCheck`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `progressCircle`,
      {
        red: 134,
        green: 181,
        blue: 246,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `radioBackground`,
      {
        red: 95,
        green: 103,
        blue: 117,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `radioBackgroundChecked`,
      {
        red: 123,
        green: 175,
        blue: 241,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `returnToCallBackground`,
      {
        red: 116,
        green: 160,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `sharedMedia_linkPlaceholder`,
      {
        red: 40,
        green: 46,
        blue: 50,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `sharedMedia_linkPlaceholderText`,
      {
        red: 80,
        green: 88,
        blue: 103,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `sharedMedia_startStopLoadIcon`,
      {
        red: 116,
        green: 167,
        blue: 239,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `stickers_menu`,
      {
        red: 106,
        green: 110,
        blue: 114,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `stickers_menuSelector`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 17,
      } as Color,
    ] as [string, Color],
    [
      `switch2Track`,
      {
        red: 223,
        green: 104,
        blue: 99,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchThumb`,
      {
        red: 60,
        green: 60,
        blue: 60,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchThumbChecked`,
      {
        red: 48,
        green: 120,
        blue: 168,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrack`,
      {
        red: 97,
        green: 105,
        blue: 122,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlue`,
      {
        red: 93,
        green: 99,
        blue: 113,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueChecked`,
      {
        red: 162,
        green: 190,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueSelector`,
      {
        red: 185,
        green: 221,
        blue: 250,
        alpha: 25,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueSelectorChecked`,
      {
        red: 122,
        green: 163,
        blue: 223,
        alpha: 50,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueThumb`,
      {
        red: 62,
        green: 64,
        blue: 73,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackBlueThumbChecked`,
      {
        red: 106,
        green: 123,
        blue: 172,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `switchTrackChecked`,
      {
        red: 115,
        green: 151,
        blue: 219,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `undo_background`,
      {
        red: 67,
        green: 71,
        blue: 80,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `undo_cancelColor`,
      {
        red: 142,
        green: 184,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundChecked`,
      {
        red: 106,
        green: 123,
        blue: 172,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundGray`,
      {
        red: 48,
        green: 49,
        blue: 53,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundUnchecked`,
      {
        red: 62,
        green: 64,
        blue: 73,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhite`,
      {
        red: 53,
        green: 56,
        blue: 62,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlackText`,
      {
        red: 255,
        green: 255,
        blue: 255,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueButton`,
      {
        red: 129,
        green: 168,
        blue: 230,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueHeader`,
      {
        red: 137,
        green: 185,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueIcon`,
      {
        red: 124,
        green: 169,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText2`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText3`,
      {
        red: 130,
        green: 171,
        blue: 237,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText4`,
      {
        red: 108,
        green: 164,
        blue: 229,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText5`,
      {
        red: 128,
        green: 177,
        blue: 240,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText6`,
      {
        red: 103,
        green: 151,
        blue: 231,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteBlueText7`,
      {
        red: 108,
        green: 173,
        blue: 232,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayIcon`,
      {
        red: 114,
        green: 126,
        blue: 135,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText`,
      {
        red: 116,
        green: 124,
        blue: 133,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText2`,
      {
        red: 116,
        green: 124,
        blue: 133,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText3`,
      {
        red: 120,
        green: 128,
        blue: 137,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText4`,
      {
        red: 109,
        green: 114,
        blue: 128,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText6`,
      {
        red: 118,
        green: 127,
        blue: 136,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGrayText8`,
      {
        red: 117,
        green: 130,
        blue: 140,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGreenText`,
      {
        red: 101,
        green: 219,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteGreenText2`,
      {
        red: 108,
        green: 215,
        blue: 141,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteHintText`,
      {
        red: 94,
        green: 105,
        blue: 117,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteInputField`,
      {
        red: 62,
        green: 69,
        blue: 75,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteInputFieldActivated`,
      {
        red: 134,
        green: 180,
        blue: 247,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteLinkSelection`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 51,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteLinkText`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteRedText2`,
      {
        red: 242,
        green: 99,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteRedText4`,
      {
        red: 242,
        green: 99,
        blue: 102,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteRedText5`,
      {
        red: 243,
        green: 97,
        blue: 104,
        alpha: 255,
      } as Color,
    ] as [string, Color],
    [
      `windowBackgroundWhiteValueText`,
      {
        red: 134,
        green: 183,
        blue: 250,
        alpha: 255,
      } as Color,
    ] as [string, Color],
  ]);

export default graphite;
